[package]
name = "rs_source"
version = "0.1.0"
authors = ["1BADragon <6611786+MattBrownCA@users.noreply.github.com>"]
edition = "2018"

[build-dependencies]
bindgen = "0.54.0"

[dependencies]
libc = "0.2.70"
linked_list_allocator = "0.8.4"

[lib]
name = "rs_source"
crate-type = ['staticlib']
